# -*- coding: utf-8 -*-
"""revision_0_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14HHBro4KWyKO1PmvYIxFF91kzAGlZidv
"""

# ============================================================
# REVISION 0
# Electricity Demand Forecasting Project
# Initial Data Exploration and Exploratory Data Analysis (EDA)
# ============================================================

import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")


# ============================================================
# 1. DATA LOADING & UNDERSTANDING
# ============================================================

def load_data(file_path):

    print("=" * 65)
    print("REVISION 0 - INITIAL DATA EXPLORATION")
    print("=" * 65)

    df = pd.read_csv(file_path)

    # Known dataset column mapping
    column_map = {
        "Timestamp": "timestamp",
        "Date": "timestamp",
        "load_MW": "MW",
        "Weather Condition": "Weather_Condition",
        "Holiday Type": "Holiday_Type",
        "Festival Name": "Festival_Name",
        "Temp": "Temp",
        "Humidity": "Humidity"
    }

    df.rename(columns=column_map, inplace=True)

    print("\n[1] DATASET OVERVIEW")
    print("-" * 40)

    print(f"Dataset shape : {df.shape}")
    print(f"Number of rows: {len(df)}")
    print(f"Number of columns: {len(df.columns)}")

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData types:")
    print(df.dtypes)

    print("\nFirst 5 observations:")
    print(df.head())

    print("\nLast 5 observations:")
    print(df.tail())

    return df


# ============================================================
# 2. DATA QUALITY
# ============================================================

def data_quality(df):

    print("\n[2] DATA QUALITY CHECK")
    print("-" * 40)

    # Missing values
    print("\nMissing values:")
    print(df.isna().sum())

    missing_percentage = df.isna().mean() * 100

    print("\nMissing percentage:")
    print(missing_percentage.round(2))

    # Duplicate records
    print(f"\nDuplicate rows: {df.duplicated().sum()}")

    # Timestamp conversion
    df["Datetime"] = pd.to_datetime(
        df["timestamp"],
        dayfirst=True,
        format="mixed",
        errors="coerce"
    )

    invalid_dates = df["Datetime"].isna().sum()

    print(f"Invalid timestamps: {invalid_dates}")

    # Date range
    if invalid_dates < len(df):

        print(f"Start date: {df['Datetime'].min()}")
        print(f"End date  : {df['Datetime'].max()}")

    # Missing-value visualization
    plt.figure(figsize=(9, 4))

    df.isna().sum().plot(kind="bar")

    plt.title("Missing Values by Variable")
    plt.ylabel("Number of Missing Values")
    plt.xlabel("Variable")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

    return df


# ============================================================
# 3. DESCRIPTIVE STATISTICS
# ============================================================

def descriptive_statistics(df):

    print("\n[3] DESCRIPTIVE STATISTICS")
    print("-" * 40)

    print(df.describe())

    # Numerical distributions
    numerical_columns = df.select_dtypes(
        include=np.number
    ).columns

    for column in numerical_columns:

        plt.figure(figsize=(7, 4))

        sns.histplot(
            df[column].dropna(),
            bins=40,
            kde=True
        )

        plt.title(f"Distribution of {column}")
        plt.xlabel(column)
        plt.ylabel("Frequency")
        plt.tight_layout()
        plt.show()


# ============================================================
# 4. ELECTRICITY DEMAND EDA
# ============================================================

def demand_eda(df):

    print("\n[4] ELECTRICITY DEMAND EDA")
    print("-" * 40)

    # Convert timestamp and sort
    df = df.dropna(subset=["Datetime"]).copy()
    df = df.sort_values("Datetime")

    df = df.set_index("Datetime")

    # Demand statistics
    print(f"Average demand : {df['MW'].mean():.2f} MW")
    print(f"Maximum demand : {df['MW'].max():.2f} MW")
    print(f"Minimum demand : {df['MW'].min():.2f} MW")

    peak_time = df["MW"].idxmax()
    minimum_time = df["MW"].idxmin()

    print(f"Peak demand time    : {peak_time}")
    print(f"Minimum demand time : {minimum_time}")

    # Historical demand
    plt.figure(figsize=(15, 5))

    plt.plot(
        df.index,
        df["MW"],
        linewidth=0.8
    )

    plt.title("Historical Electricity Demand")
    plt.xlabel("Date")
    plt.ylabel("Demand (MW)")
    plt.tight_layout()
    plt.show()

    # Time features for EDA only
    df["Hour"] = df.index.hour
    df["Day_of_Week"] = df.index.dayofweek
    df["Month"] = df.index.month

    # Hourly pattern
    plt.figure(figsize=(10, 5))

    sns.boxplot(
        data=df,
        x="Hour",
        y="MW"
    )

    plt.title("Electricity Demand by Hour")
    plt.xlabel("Hour of Day")
    plt.ylabel("Demand (MW)")
    plt.tight_layout()
    plt.show()

    # Day-of-week pattern
    plt.figure(figsize=(10, 5))

    sns.boxplot(
        data=df,
        x="Day_of_Week",
        y="MW"
    )

    plt.title("Electricity Demand by Day of Week")
    plt.xlabel("Day of Week (0 = Monday)")
    plt.ylabel("Demand (MW)")
    plt.tight_layout()
    plt.show()

    # Monthly pattern
    plt.figure(figsize=(10, 5))

    sns.boxplot(
        data=df,
        x="Month",
        y="MW"
    )

    plt.title("Electricity Demand by Month")
    plt.xlabel("Month")
    plt.ylabel("Demand (MW)")
    plt.tight_layout()
    plt.show()

    return df


# ============================================================
# 5. WEATHER EDA
# ============================================================

def weather_eda(df):

    print("\n[5] WEATHER EDA")
    print("-" * 40)

    if "Temp" in df.columns:

        print(
            f"Temperature range: "
            f"{df['Temp'].min():.1f} to "
            f"{df['Temp'].max():.1f}"
        )

        plt.figure(figsize=(7, 5))

        sns.scatterplot(
            data=df,
            x="Temp",
            y="MW",
            alpha=0.25
        )

        plt.title("Temperature vs Electricity Demand")
        plt.xlabel("Temperature")
        plt.ylabel("Demand (MW)")
        plt.tight_layout()
        plt.show()

    if "Humidity" in df.columns:

        plt.figure(figsize=(7, 5))

        sns.scatterplot(
            data=df,
            x="Humidity",
            y="MW",
            alpha=0.25
        )

        plt.title("Humidity vs Electricity Demand")
        plt.xlabel("Humidity")
        plt.ylabel("Demand (MW)")
        plt.tight_layout()
        plt.show()

    if "Weather_Condition" in df.columns:

        plt.figure(figsize=(9, 5))

        sns.boxplot(
            data=df,
            x="Weather_Condition",
            y="MW"
        )

        plt.title("Electricity Demand by Weather Condition")
        plt.xlabel("Weather Condition")
        plt.ylabel("Demand (MW)")
        plt.xticks(rotation=30)
        plt.tight_layout()
        plt.show()


# ============================================================
# 6. HOLIDAY & FESTIVAL EDA
# ============================================================

def calendar_eda(df):

    print("\n[6] HOLIDAY & FESTIVAL EDA")
    print("-" * 40)

    if "Holiday_Type" in df.columns:

        print("\nHoliday distribution:")
        print(df["Holiday_Type"].value_counts(dropna=False))

        plt.figure(figsize=(9, 5))

        sns.boxplot(
            data=df,
            x="Holiday_Type",
            y="MW"
        )

        plt.title("Electricity Demand by Holiday Type")
        plt.xlabel("Holiday Type")
        plt.ylabel("Demand (MW)")
        plt.xticks(rotation=30)
        plt.tight_layout()
        plt.show()

    if "Festival_Name" in df.columns:

        print("\nFestival distribution:")
        print(df["Festival_Name"].value_counts(dropna=False).head(15))

        # Only show the most frequent festival categories
        top_festivals = (
            df["Festival_Name"]
            .value_counts()
            .head(10)
            .index
        )

        festival_df = df[
            df["Festival_Name"].isin(top_festivals)
        ]

        if len(festival_df) > 0:

            plt.figure(figsize=(10, 5))

            sns.boxplot(
                data=festival_df,
                x="Festival_Name",
                y="MW"
            )

            plt.title("Electricity Demand for Major Festival Categories")
            plt.xlabel("Festival")
            plt.ylabel("Demand (MW)")
            plt.xticks(rotation=45)
            plt.tight_layout()
            plt.show()


# ============================================================
# 7. INITIAL CORRELATION ANALYSIS
# ============================================================

def correlation_analysis(df):

    print("\n[7] INITIAL CORRELATION ANALYSIS")
    print("-" * 40)

    numerical_df = df.select_dtypes(include=np.number)

    correlation = numerical_df.corr()

    print("\nCorrelation with electricity demand:")
    print(
        correlation["MW"]
        .sort_values(ascending=False)
    )

    plt.figure(figsize=(9, 7))

    sns.heatmap(
        correlation,
        annot=True,
        fmt=".2f"
    )

    plt.title("Correlation Matrix")
    plt.tight_layout()
    plt.show()


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    FILE_PATH = "load_data.csv"

    df = load_data(FILE_PATH)

    df = data_quality(df)

    descriptive_statistics(df)

    df = demand_eda(df)

    weather_eda(df)

    calendar_eda(df)

    correlation_analysis(df)

    print("\n" + "=" * 65)
    print("REVISION 0 COMPLETE")
    print("Initial EDA completed. ML modelling is intentionally excluded.")
    print("=" * 65)
